http:
  private:
    host: "0.0.0.0"
    port: "8091"

pbcsAPI:
  basePath: "/interop/rest/11.1.2.3.600/"
  path: "/applicationsnapshots/"
  dailycontracts_path: "/applicationsnapshots/Daily Contract Information.CSV/contents"
  host: "planning-a601519.pbcs.em3.oraclecloud.com"
  port: "443"
  username: "a601519.INTERGRATION_PROD"
  password: "![cBnue2TGeRh237MlJ40zY/hamsYpiqHV]"
    
api:
  autodiscovery:
    id: "16467017"
    flow: "sys-mapt-pbcs-gc-api-main"
  
  